version: '3'

services:
  n8n:
    image: n8nio/n8n:1.104.2
    restart: unless-stopped
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      # Basic Authentication
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      
      # n8n Configuration
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - WEBHOOK_URL=${WEBHOOK_URL}
      
      # Additional Settings (optional)
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-}
      - N8N_LOG_LEVEL=${N8N_LOG_LEVEL:-info}
      - N8N_TIMEZONE=${N8N_TIMEZONE:-UTC}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL:-}
      - N8N_METRICS=${N8N_METRICS:-false}
      - N8N_TELEMETRY_ENABLED=${N8N_TELEMETRY_ENABLED:-false}
      
      # Custom Nodes Configuration
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./nodes:/tmp/nodes:ro

